---
# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "Type: Support"

# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: >
  :wave: We use the issue tracker exclusively for bug reports and feature requests.
  However, this issue appears to be a support request. Please use our
  support channels to get help with the project.

  Head over to the
  [Home Assistant community forum](https://community.home-assistant.io/)
  or join our [Discord](https://discord.me/hassioaddons) chat.

# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: false
